config/routes.rb
Rails.application.routes.draw do
  root to: 'topics#index'
  resources :blacklists
  resources :topics do
    resources :descriptions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blacklist.rb
class Blacklist < ApplicationRecord
  has_many :topics
  has_many :descriptions
  validates :word, presence: { message: 'O campo não pode ficar em branco' },
                   uniqueness: { message: 'Essa palavra já existe',
                                 case_sensitive: false }
end

app/models/description.rb
class Description < ApplicationRecord
  belongs_to :topic
  validates :desc, presence: { message: 'O campo não pode ficar em branco' }
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :descriptions
  validates :title, presence: { message: 'Você deve informar um tópico ' },
                    uniqueness: { message: 'Esse tópico já existe',
                                  case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blacklists_controller.rb
class BlacklistsController < ApplicationController
  before_action :set_blacklist, only: %i[show edit update]

  def new
    @blacklist = Blacklist.new
  end

  def show; end

  def index
    @blacklists = Blacklist.all
    @topics = Topic.all
  end

  def create
    @blacklist = Blacklist.new(blacklist_params)
    if @blacklist.save
      redirect_to blacklists_path
    else
      render :new
    end
  end

  def edit
    @blacklist = Blacklist.find(params[:id])
  end

  def update
    if @blacklist.update(blacklist_params)
      redirect_to blacklists_path
    else
      render :edit
    end
  end

  private

  def set_blacklist
    @blacklist = Blacklist.find(params[:id])
  end

  def blacklist_params
    params.require(:blacklist).permit(:word)
  end
end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController
  def index; end

  def new
    @description = Description.new
  end

  def create
    @description = Description.new(description_params)
    @description.topic_id = params[:topic_id]
    if @description.save
      redirect_to topic_path(params[:topic_id])
    else
      @topics = Topic.new
      render :new
    end
  end

  def show; end

  private

  def description_params
    params.require(:description).permit(:desc)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    @blacklists = Blacklist.all
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @descriptions = Description.where(topic: @topic)
    @blacklists = Blacklist.all
  end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blacklists/_form.html.erb
<% @blacklist.errors.full_messages.each do |message| %>
  <div class="alert alert-warning" role="alert">
  <%= message %>
  </div>
<% end %>

<%= form_with model: blacklist, class: 'mt-4', local: true do |f| %>
  <div class="form-group">
    <%= f.label :word, 'Digite a palavra' %>
    <%= f.text_field :word, class: 'form-control col-md-6' %>
  </div>
  <%= f.submit 'Enviar', class: 'btn btn-secondary' %>
<% end %>

app/views/blacklists/edit.html.erb
<%= render partial: 'form', locals: { blacklist: @blacklist} %>

app/views/blacklists/index.html.erb
<div>
<section class="jumbotron text-center">
  <% if @blacklists.any? %>
    <ul>
      <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col"></th>
          <th scope="col">Palavra</th>
          <th scope="col"></th>
        </tr>
      </thead>  
    <% @blacklists.each_with_index do |blacklist| %>
      <tbody>
        <tr>
          <td><%= blacklist.id %></td>
          <td><%= blacklist.word %></td>
          <td>
            <%= link_to 'Editar', edit_blacklist_path(blacklist),
                                  class: 'btn btn-secondary' %>
          </td>
        </tr>
    <% end %>
      </tbody>
      </table>
    </ul>
  <% else %>
    <p class="text-center">
      Ainda não temos nenhuma palavra. Que tal enviar uma?
    </p>
    <div>
      <%= link_to 'Primeira Palavra', new_blacklist_path, 
                                  class: 'btn btn-secondary' %>
      <%= link_to 'Inicio', root_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</section>
<div>
   <%= link_to 'Nova Palavra', new_blacklist_path, class: 'btn btn-secondary' %>
  <%= link_to 'Inicio', root_path, class: 'btn btn-secondary' %>
</div>
</div>

app/views/blacklists/new.html.erb
<%= render partial: 'form', locals: { blacklist: @blacklist } %>

app/views/blacklists/show.html.erb
<section class="jumbotron text-center">
  <ul>
    <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Tópico</th>
        <th scope="col">Data</th>
        <th scope="col">Resposta</th>
        <th scope="col"></th>
      </tr>
    </thead>  
    <tbody>
      <tr>
        <td><%= @blacklist.id %></td>
        <td><%= @blacklist.word %></td>
        <td>
          <%= link_to 'Editar', edit_blacklist_path(@blacklist),
                                class: 'btn btn-secondary' %>
        </td>
      </tr>
    </tbody>
    </table>
  </ul>
</section>
<div>
   <%= link_to 'Nova Palavra', new_blacklist_path, class: 'btn btn-secondary' %>
  <%= link_to 'Inicio', root_path, class: 'btn btn-secondary' %>
</div>

app/views/descriptions/_form.html.erb
  <% @description.errors.full_messages.each do |message| %>
    <div class="alert alert-warning" role="alert">
    <%= message %>
    </div>
  <% end %>

<%= form_for @description, :url => {:controller => "descriptions", :action => "create"} do |f| %>
  <div class="form-group">
    <%= f.label :desc, 'Novo Comentário' %>
    <%= f.text_field :desc, class: 'form-control col-md-6' %>
  </div>
  <%= f.submit 'Enviar', class: 'btn btn-primary' %>
<% end %>

app/views/descriptions/new.html.erb
<%= render partial: 'form', locals: { description: @description } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="main">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>
      <% end %>
      <div class="container">
        <%= yield %>
      </div>
    </div>
    <%= render 'shared/footer' %>     
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
    <a href="#">Topo</a>
    </p>
    <p>Fórum R7 ©</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar center navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Fórum R7', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Cadastrar Tópico', new_topic_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Blacklist', blacklists_path, class: 'nav-link' %>
        </li>
      </ul>
    </ul>
    </div>
</nav>

app/views/topics/_form.html.erb
  <% @topic.errors.full_messages.each do |message| %>
    <div class="alert alert-warning" role="alert">
    <%= message %>
    </div>
  <% end %>

<%= form_with model: topic, class: 'mt-4' do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Tópico' %>
    <%= f.text_field :title, class: 'form-control col-md-6' %>
  </div>
  <%= f.submit 'Enviar', class: 'btn btn-primary' %>
<% end %>

app/views/topics/index.html.erb
<section class="jumbotron text-center">
  <h1>Fórum R7</h1>
  <p class="lead">Seja bem vindo ao melhor fórum online</p>
</section>

<%= flash[:alert] %>

<section class="jumbotron text-center">

<% if @topics.any? %>
<ul>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col"></th>
        <th scope="col">Tópico</th>
        <th scope="col">Data</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <% @topics.each_with_index do |topic, number| %>
      <tbody>
        <tr>
          <td><%= "#{number + 1}." %></td>
            <td><%= topic.title  %></td>
          <td><%= topic.created_at.to_s(:post) %></td>
          <td>
            <%= link_to 'Responder Comentário', topic_path(topic), 
                                                class: 'btn btn-secondary' %>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>
</ul>
<% else %>
  <p class="text-center">
    Ainda não temos nenhum Tópico. Que tal enviar um?
  </p>
  <div>
   <%= link_to 'Novo Tópico', new_topic_path, class: 'btn btn-secondary' %>
</div>
<% end %>
</section>

app/views/topics/new.html.erb
<%= render partial: 'form', locals: { topic: @topic } %>

app/views/topics/show.html.erb
<section class="jumbotron text-center">
  <% if @descriptions.any? %>
    <ul>
      <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Tópico</th>
          <th scope="col">Data</th>
          <th scope="col">Resposta</th>
          <th scope="col"></th>
        </tr>
      </thead>  
    <% @descriptions.each_with_index do |description, number| %>
      <tbody>
        <tr>
          <td><%= @topic.id %></td>
          <td><%= description.created_at.to_s(:post) %></td>
          <td><%= description.desc %></td>
          <td>
            <%= link_to 'Responder Comentário', new_topic_description_path(@topic, description),
                                                class: 'btn btn-secondary' %>
          </td>
        </tr>
    <% end %>
      </tbody>
      </table>
    </ul>
  <% else %>
    <p class="text-center">
      Ainda não temos nenhuma resposta. Que tal enviar uma?
    </p>
    <div>
      <%= link_to 'Nova Resposta', new_topic_description_path(@topic), class: 'btn btn-secondary' %>
      <%= link_to 'Voltar', root_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</section>
<div>
   <%= link_to 'Nova Resposta', new_topic_description_path(@topic), class: 'btn btn-secondary' %>
  <%= link_to 'Voltar', root_path, class: 'btn btn-secondary' %>
</div>

  